### ISSUE TITLE
First/Trial_issue

### ISSUE THREAD

**Issue by LiZoMark841619** [JorgeValencia97/CC_Frida_Retrospective#1]
The code seemed okay. I used .append() to add new elements to the list, but your solution is good too. Otherwise I use this in order to get started, I have not used this before. :D

**Comment by JorgeValencia97** [comment]
Thank you very much for your comment. Regarding the append method, the problem I see is you have to add one by one the new elements. That's why I use +=, or even, you can use the extend method as well. Happy Coding!
